# Generated by Django 4.2.3 on 2023-07-17 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_type_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=20, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('number', models.CharField(max_length=20, verbose_name='Numero')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Edad')),
                ('direction', models.CharField(max_length=150, verbose_name='Direccion')),
                ('sex', models.CharField(max_length=70, verbose_name='Sexo')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('od_sph', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='0.00')),
                ('od_cyl', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='-0.00')),
                ('od_axis', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='180')),
                ('od_add', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='0.00')),
                ('od_prism', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='0.00')),
                ('od_base', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='0.00')),
                ('od_dip', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='60/62')),
                ('od_alt', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='25')),
                ('oi_sph', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='0.00')),
                ('oi_cyl', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='-0.00')),
                ('oi_axis', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='180')),
                ('oi_add', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='0.00')),
                ('oi_prism', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='0.00')),
                ('oi_base', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='0.00')),
                ('oi_dip', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='60/62')),
                ('oi_alt', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='25')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('qty', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='detsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale'),
        ),
    ]
