# Generated by Django 4.2.3 on 2023-07-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_category_client_detsale_product_sale_delete_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='od_add',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='0.00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='od_alt',
            field=models.PositiveIntegerField(default=25, verbose_name='25'),
        ),
        migrations.AlterField(
            model_name='client',
            name='od_axis',
            field=models.PositiveIntegerField(max_length=3, verbose_name='180'),
        ),
        migrations.AlterField(
            model_name='client',
            name='od_base',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='0.00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='od_cyl',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='-0.00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='od_dip',
            field=models.CharField(max_length=6, verbose_name='60/62'),
        ),
        migrations.AlterField(
            model_name='client',
            name='od_prism',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='0.00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='od_sph',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='0.00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='oi_add',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='0.00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='oi_alt',
            field=models.PositiveIntegerField(default=25, verbose_name='25'),
        ),
        migrations.AlterField(
            model_name='client',
            name='oi_axis',
            field=models.PositiveIntegerField(max_length=3, verbose_name='180'),
        ),
        migrations.AlterField(
            model_name='client',
            name='oi_base',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='0.00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='oi_cyl',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='-0.00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='oi_dip',
            field=models.CharField(max_length=6, verbose_name='60/62'),
        ),
        migrations.AlterField(
            model_name='client',
            name='oi_prism',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='0.00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='oi_sph',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='0.00'),
        ),
    ]
