# Generated by Django 4.2.3 on 2023-07-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_client_od_add_alter_client_od_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='oi_cyl',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Cilindro'),
        ),
    ]
